on:
  workflow_call:
    inputs:
      service-name:
        description: "The name of the service"
        required: true
        type: string
      image-tag:
        description: "The tag for the Docker image"
        required: true
        type: string
      image-name:
        description: "The name of the Docker image"
        required: true
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.service-name }}
          push: true
          tags: ghcr.io/microservices-tta/architecture-microservices/${{ inputs.image-name }}:${{ inputs.image-tag }}
