on:
  workflow_call:
    inputs:
      service-name:
        description: "The name of the service"
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Restore Node.js modules
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ inputs.service-name }}/node_modules
            ${{ inputs.service-name }}/.cache
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Test ${{ inputs.service-name }}
        working-directory: ${{ inputs.service-name }}
        run: npm run test
